### ISSUE TITLE
Arbitrary HTML tags within posts should be escaped

### ISSUE THREAD

**Issue by psybuzz** [psybuzz/goldenconversations#14]
Today, arbitrary HTML tags in posts are simply inserted into the DOM.  When we save a newly created post, our backend should sanitize the input by escaping special characters.

Perhaps using the Validator node package?
https://www.npmjs.org/package/validator

**Comment by tonyxj** [comment]
Hi Guys, I've revisited this bug, trying HTML tags in both conversations name and conversation thread. This is the result: 
![image](https://cloud.githubusercontent.com/assets/6765882/5607744/97d700cc-941c-11e4-82eb-d46a0e76b19a.png)

It appears that the tags in the thread are escaped but the title is not? Should we worry about the title escaping HTML tags?

**Comment by psybuzz** [comment]
I'm glad you found that, Tony!  I think it is a valid concern.  It would look nicer if titles appeared as they were typed in, and it would also be more consistent behavior if the user expects the post content to be the same as the title.

I can make a short PR that should address this.  Thanks for finding it!

**Comment by nikilselvam** [comment]
Yeah, I agree that it would be best if titles appeared as they were typed in. It'll create a nice user experience!

**Comment by tonyxj** [comment]
:+1:

**Comment by tonyxj** [comment]
Closing. As this is fixed on stable.
