### ISSUE TITLE
Conversations disappeard

### ISSUE THREAD

**Issue by tonyxj** [psybuzz/goldenconversations#48]
Also, I don't see the conversations in the app. When I log in all of my previous conversations, including the one Nikil just started are not there. This is one type of bug that particularly bothersome for an app like GC! 

I'm not sure if this is related to me having two accounts or the new archiving feature. Would you guys mind taking a look in the backend and shed some light? @psybuzz @nikilselvam 
Thanks!

![image](https://cloud.githubusercontent.com/assets/6765882/5734423/f6cc2ec8-9b69-11e4-86e2-70bc9ade61c8.png)

**Comment by psybuzz** [comment]
!!!
That is extremely strange.  Can you open up the JS console on that page and let us know if there are any errors?  Let us know if you see any errors or anything strange.

I'm still able to see my convos, and I couldn't find anything seriously strange in the Heroku logs in the past 10 minutes.  If anything, I'd say your having multiple accounts might be causing this.  On MongoLab, one of your accounts has 0 conversations while another has 4.  If you see no JS console errors, it might be a good idea for us to delete the empty duplicate account.

**Comment by tonyxj** [comment]
It appears that there are no errors. Should we try deleting the account with 0 conversations see what happens?

![image](https://cloud.githubusercontent.com/assets/6765882/5734573/da140776-9b6c-11e4-93ae-af964548dea9.png)

**Comment by psybuzz** [comment]
Sounds good, I'll delete the ghost Tony now.

**Comment by tonyxj** [comment]
So long my #doppelganger!

**Comment by psybuzz** [comment]
Haha, the twin is gone!  Let us know if you can see your convo's again.

**Comment by tonyxj** [comment]
Awesome possum, the conversations are back!

**Comment by psybuzz** [comment]
Terminator: I'll be back.
Paul Revere: The British are coming!
Tony: The conversations are back!

...I see a trend

**Comment by tonyxj** [comment]
Back in the NY groove! 

On a side note, I've archived two conversations, but they don't show up in HOF. That's expected right?
![image](https://cloud.githubusercontent.com/assets/6765882/5734713/0d0b8152-9b6f-11e4-9a78-ceb38ddf7010.png)

**Comment by psybuzz** [comment]
Yup, it's all A-OK!

**Comment by tonyxj** [comment]
aww yeah!
